DATA SEGMENT
	N1 DW 000AH
	N2 DW 0002H
	GCD DW ?
	MSG DB 10, 13, 'GCD OF THE GIVEN NUMBERS ARE: $'
DATA ENDS

CODE SEGMENT
	ASSUME DS:DATA, CS:CODE
	START: MOV AX, DATA
		   MOV DS, AX
		   MOV BX, N1
		   MOV CX, N2
	BACK:  CMP BX, CX
		   JE EXIT
		   CMP CX, 0
		   JE EXIT
		   MOV AX, BX
		   XOR DX, DX
		   DIV CX
		   MOV CX, DX
		   JMP BACK
	EXIT: MOV GCD, BX
		  MOV AH, 09H
		  LEA DX, MSG
		  INT 21H
		  MOV AX, BX
		  AAM
		  ADD AX, 3030H
		  MOV BX, AX
		  MOV AH, 02H
		  MOV DL, BH
		  INT 21H
		  MOV DL, BL
		  INT 21H
		  MOV AH, 4CH
		  INT 21H
CODE ENDS
END START
		  
		  